"""
The LiDAR point clouds are generated, and must be gated like the rest of the
Airoli showcase.

This is not a formality. Both modules build their response bodies from literals
rather than from a loaded dataset: `lidar_inspect.get_scene` assembles a
provenance block naming a file, and `lidar.get_lidar_pointcloud` returns a
building name, a permitted FSI and a point count. So with ``ENABLE_DEMO_MODE``
unset - the default in ``docker-compose.yml``, which every non-demo deployment
inherits - they still answered 200 and described an airborne survey that was
never flown, while the rest of the app correctly refused.

Every route that serves generated points is listed explicitly rather than
discovered, so a route added later is not covered by accident. If one is added,
it fails here until someone decides whether it is demo data, which is the
decision that was missed the first time.
"""
import pytest


def _client():
    from fastapi.testclient import TestClient
    from app.main import app
    return TestClient(app)


GENERATED_LIDAR_ROUTES = [
    ("GET", "/api/v1/lidar/inspect/scene", {}),
    ("GET", "/api/v1/lidar/inspect/points", {}),
    ("GET", "/api/v1/lidar/pointcloud", {}),
    ("GET", "/api/v1/lidar/pointcloud/binary", {}),
]


@pytest.mark.parametrize("method,path,kwargs", GENERATED_LIDAR_ROUTES)
def test_generated_lidar_is_gated_by_default(monkeypatch, method, path, kwargs):
    """With the demo gate shut, no generated point cloud is served."""
    from fastapi.testclient import TestClient
    from app.main import app

    # conftest sets ENABLE_DEMO_MODE=1 suite-wide; this is about the default
    # deployment, so force it the way a real deployment would have it.
    monkeypatch.setenv("ENABLE_DEMO_MODE", "0")

    client = TestClient(app)
    res = getattr(client, method.lower())(path, **kwargs)
    assert res.status_code == 503, (
        f"{method} {path} returned {res.status_code} with ENABLE_DEMO_MODE off; "
        "it must refuse to serve generated points, and must not answer with a "
        "point count or a provenance block describing a survey never flown"
    )
    # The refusal has to say why, or the UI shows a bare 503.
    detail = res.json().get("detail", "")
    assert "demo" in detail.lower(), f"{path} refusal does not explain itself: {detail!r}"


def test_scene_provenance_does_not_claim_a_vendor_delivery(monkeypatch):
    """The source string must not read like a delivery from a survey vendor.

    It used to be ``alms:airoli_s8_hero.las``. No ALMS delivery ever happened;
    the file was generated by this project, and its own ``metadata.json`` says
    so. A ``source`` field is what a reader trusts before reading anything
    else, which makes it the worst place for a prefix that implies provenance
    nobody can produce.
    """
    from pathlib import Path

    from app.api.v1 import lidar_inspect

    monkeypatch.setenv("ENABLE_DEMO_MODE", "1")

    # LAS_PATH is the absolute in-container location, which does not exist when
    # the suite runs on the host. Point it at the file that actually ships, so
    # this asserts on the response body rather than skipping: a skipped test here
    # would be a skipped test everywhere, since the path is wrong in both places.
    repo_las = Path(__file__).resolve().parents[1] / "data" / "sample_pointcloud" / "airoli_s8_hero.las"
    if not repo_las.exists():
        pytest.skip("point-cloud dataset is not present in this checkout")
    monkeypatch.setattr(lidar_inspect, "LAS_PATH", str(repo_las))

    res = _client().get("/api/v1/lidar/inspect/scene")
    assert res.status_code == 200, f"scene failed to load the dataset: {res.status_code} {res.text[:200]}"

    source = res.json()["dataset"]["source"].lower()
    assert not source.startswith("alms"), f"provenance still implies a vendor delivery: {source!r}"
    assert res.json()["dataset"]["demo"] is True
    assert "synthetic" in res.json()["dataset"]["demo_note"].lower()
