"""Rank buildings by how much a floor survey is worth, using the floor estimator.

The estimator's own verdict says it cannot delineate vertical parcels (MAE 2.1
floors). What it *can* do is say where its own uncertainty is worst, which is
the question a surveyor's day is actually shaped by: there are 45,489 buildings
in ``national_twins`` and finite surveyor-hours. A triage queue that ranks them
by expected survey value is the one use the model is fit for, and it is a real
application of the model rather than a demo endpoint.

How the ranking works, and what it deliberately is not

Score is ``uncertainty x exposure``:

- ``uncertainty`` is the spread of the forest's per-tree predictions for that
  building (p90 - p10 across trees). Wide spread means the trees disagree, which
  is a genuine signal of ambiguity from the footprint alone.
- ``exposure`` is footprint area, as a proxy for how many dwellings sit in the
  stack and therefore how much ownership ambiguity a wrong floor count creates.

This is **not** a claim that the top-ranked buildings have the largest errors.
Uncertainty here is model disagreement, not measured error; a building can be
confidently wrong. The ranking says "survey here first", never "this building is
wrong". ``get_triage_queue`` says so in its own response, and the tests hold it
to that.

Neither input is usable as published. The area comes from ``national_twins``
footprints, which are parcel-sized ``shapely_box`` polygons rather than buildings,
and the model was fitted to ``floors = random.randint(...)`` over that same
table. So the disagreement being ranked is the spread of a model learning a
generator, not genuine survey uncertainty.

``load_model`` returns ``None`` unless the manifest carries a passing label
provenance audit, so with the current data this endpoint reports that no model
is available rather than serving a fabricated ranking.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

ARTIFACT_DIR = Path(__file__).resolve().parents[1] / "ml" / "artifacts"
MANIFEST_PATH = ARTIFACT_DIR / "floor_estimator_manifest.json"
AUDIT_PATH = ARTIFACT_DIR / "label_provenance_audit.json"
MODEL_PATH = ARTIFACT_DIR / "floor_estimator.joblib"


def load_manifest() -> dict[str, Any] | None:
    if not MANIFEST_PATH.exists():
        return None
    return json.loads(MANIFEST_PATH.read_text())


def load_label_provenance_audit() -> dict[str, Any]:
    """Read the label audit the trainer writes, defaulting to unusable.

    An absent audit means no model is served. Absence is treated as failure
    rather than as "unreviewed but probably fine", because the artefact that
    motivated this gate is precisely a model whose label was generated.
    """
    if not AUDIT_PATH.exists():
        return {
            "verdict": "not_audited",
            "usable_as_label": False,
            "reason": "no label provenance audit on disk",
        }
    try:
        return json.loads(AUDIT_PATH.read_text())
    except (OSError, ValueError):
        return {
            "verdict": "unreadable_audit",
            "usable_as_label": False,
            "reason": f"could not parse {AUDIT_PATH.name}",
        }


def load_model():
    """Load the fitted forest, or None when it must not be served.

    Returns None rather than raising: the endpoint that serves the queue must be
    able to say "not available" with a reason, which is more useful to a reader
    than a 500.

    The manifest gate is the point of this function. A model exists on disk from
    an earlier fit against ``national_twins``, whose ``floors`` column was
    generated by ``random.randint``. Serving it would rank real survey
    prioritisation off a fitted artefact, so a manifest without a passing label
    provenance audit is treated as no model at all.
    """
    if not MODEL_PATH.exists():
        return None

    audit = load_label_provenance_audit()
    if not audit.get("usable_as_label"):
        return None

    import joblib

    return joblib.load(MODEL_PATH)


def rank_by_survey_value(
    predictions: np.ndarray,
    tree_predictions: np.ndarray,
    areas_m2: np.ndarray,
    ulpins: list[str],
    limit: int = 50,
) -> list[dict[str, Any]]:
    """Rank buildings by ``uncertainty x exposure``.

    ``tree_predictions`` is ``(n_trees, n_buildings)``. Spread is the 10th to
    90th percentile across trees, which is robust to a couple of odd trees and
    does not assume the trees' outputs are normally distributed. Reported as an
    interval rather than a confidence, because a random forest has no
    calibrated distribution and inventing one would be the same mistake as
    reporting a probability for an unvalidated model.
    """
    if tree_predictions.size == 0:
        return []
    p10 = np.percentile(tree_predictions, 10, axis=0)
    p90 = np.percentile(tree_predictions, 90, axis=0)
    spread = p90 - p10
    exposure = np.sqrt(np.maximum(areas_m2, 0.0))  # area^0.5, so doubling area is not 4x
    score = spread * exposure

    order = np.argsort(-score)[:limit]
    out: list[dict[str, Any]] = []
    for idx in order:
        out.append(
            {
                "ulpin": ulpins[idx],
                "floors_predicted": round(float(predictions[idx]), 2),
                "floors_lo": int(np.floor(p10[idx])),
                "floors_hi": int(np.ceil(p90[idx])),
                "tree_spread_floors": round(float(spread[idx]), 2),
                "footprint_area_m2": round(float(areas_m2[idx]), 2),
                "survey_value_score": round(float(score[idx]), 3),
                "recommended_action": "FLOOR_SURVEY",
                "authority": "none",
            }
        )
    return out


def get_triage_queue(limit: int = 50, sample_cap: int = 45000) -> dict[str, Any]:
    """Build the triage response, including everything that qualifies it."""
    manifest = load_manifest()
    if manifest is None:
        return {
            "available": False,
            "reason": (
                "floor estimator has not been trained; run "
                "PYTHONPATH=backend python -m app.ml.train_floor_estimator"
            ),
            "buildings": [],
        }

    model = load_model()
    if model is None:
        audit = load_label_provenance_audit()
        if not audit.get("usable_as_label"):
            return {
                "available": False,
                "reason": (
                    "the training label failed its provenance audit, so no model is "
                    "served: "
                    + "; ".join(audit.get("reasons", [audit.get("reason", audit["verdict"])]))
                    + ". Re-running training will not help; it refuses on the same "
                    "check. Retraining needs a genuinely observed floor count."
                ),
                "label_provenance": audit,
                "buildings": [],
            }
        return {
            "available": False,
            "reason": (
                "the manifest exists and the label passed audit, but "
                "floor_estimator.joblib is absent; re-run training to regenerate "
                "the fitted model"
            ),
            "buildings": [],
        }

    from sqlalchemy import create_engine, text

    from app.core.config import settings

    url = settings.DATABASE_URL
    sync_url = url.replace("postgresql+asyncpg://", "postgresql+psycopg2://")
    engine = create_engine(sync_url)
    try:
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    """
                    SELECT ulpin,
                           ST_Area(footprint_polygon) AS area_m2,
                           ST_Perimeter(footprint_polygon) AS perimeter_m,
                           ST_X(ST_PointOnSurface(footprint_polygon)) AS cx,
                           ST_Y(ST_PointOnSurface(footprint_polygon)) AS cy,
                           ST_NPoints(footprint_polygon) AS vertex_count,
                           ST_XMin(footprint_polygon) AS minx, ST_XMax(footprint_polygon) AS maxx,
                           ST_YMin(footprint_polygon) AS miny, ST_YMax(footprint_polygon) AS maxy,
                           floor(ST_X(ST_PointOnSurface(footprint_polygon)) / 0.01) AS gx,
                           floor(ST_Y(ST_PointOnSurface(footprint_polygon)) / 0.01) AS gy
                    FROM national_twins
                    WHERE footprint_polygon IS NOT NULL
                    LIMIT :cap
                    """
                ),
                {"cap": sample_cap},
            ).fetchall()
    finally:
        engine.dispose()

    from app.ml.train_floor_estimator import _build_matrix

    feats, _y, _cells = _build_matrix([dict(r._mapping) for r in rows])
    X = np.array(feats, dtype=np.float32)
    ulpins = [r.ulpin for r in rows]
    areas = np.array([float(r.area_m2 or 0.0) for r in rows], dtype=np.float32)

    preds = model["model"].predict(X)
    tree_preds = np.array([t.predict(X) for t in model["model"].estimators_])

    ranked = rank_by_survey_value(preds, tree_preds, areas, ulpins, limit=limit)

    return {
        "available": True,
        "n_considered": len(rows),
        "n_ranked": len(ranked),
        "buildings": ranked,
        "ranking_basis": (
            "tree prediction spread (p90-p10) x sqrt(footprint area). Ranked by "
            "expected survey value, not by measured error."
        ),
        "is_not": (
            "This is not a list of buildings known to be wrong. Model "
            "disagreement is a proxy for ambiguity, not evidence of error, and a "
            "confidently wrong building will not appear here."
        ),
        "authority": "none",
        "inputs_authoritative": False,
        "label_source": manifest.get("label_source"),
        "estimator_metrics": manifest.get("metrics_geographic_split"),
        "estimator_fitness": manifest.get("fitness"),
        "limitations": manifest.get("limitations"),
        "n_cap_note": (
            f"scored the first {sample_cap} buildings by insertion order, not a "
            "random sample, so the queue is representative of row order rather "
            "than of the city"
        ),
    }